#Please note:
    #This function outputs the daily average PAF (Potentially Affected Fraction) for the 4 classes of pesticides:
        #photosystem II herbicides(PSII), other herbicides (OTHER HERBICIDES), insecticides (INSECTICIDES) and all 22 pesticides (TOTAL) using the Independent Action model of joint action.
    #This function has been created to provide the daily average PAF as input data for the Multiple Imputation (MI) method that calculates the average PAF (Pesticide Risk Metric) over the wet season (i.e. first flush + 182 days) for each site/year combination.
    #This script outputs Daily Average PAF values for each of the 4 classes into a user specified location.
    #The location of these folders can be found/changed under the 'Daily Average Tab' section of this script
    #All SSD distributions were estimated in Burrlioz 2.0 (CSIRO). 
    #HK has ammended this script to NOT average daily PAF, instead it will calculate paf for all dates/ times. Time needs to be kept in data for this to happen

#The input data for this function needs to contain:
#Treated LOR values
#Date with TIME so PAF is obtained for each sample
#STATION = Station number
#SITENAME = Site name
#Sampling.Year = Sampling year
#Concentration data for all 22 pesticides


####################
#SSD PARAMETERS TAB 
####################
#Burrlioz 2.0 (CSIRO) identifies the best fitting distribution for the SSD's and provides the estimated parameters used below.
#Warning: Changes must not be made to the SSD PARAMETERS TAB

calculate_Daily_Average_IA_PAF_Categories <- function(pesticide_dataset, output_path){
  
 
 
  SITENAME <- pesticide_dataset$SITENAME
  
  STATION <- pesticide_dataset$STATION
  
  SAMPLING.YEAR <- pesticide_dataset$Sampling.Year
  
  #Variable for DATE HK change from date to date time
    SAMPLING.DATE <- pesticide_dataset$DATE.TIME.SAMPLED
  
  ###4-HPPD Inhibitors
      #Alpha & Beta values exponentiated to antilog - all alpha & beta values used in the Independent Action calculations mathematically describe the species sensitivity distribution (SSD) generated by Burrlioz for each pesticide. The default log used is natural log
      Isoxaflutole_parameters <- data.frame(Pesticide.type = "Herbicide", Distribution.type ="Inverse Weibull", log.alpha = -0.385904591, alpha = 0.679835385, log.beta = -1.242018461, beta = 0.288800696)
      
  ###ACCase Inhibitors
      #Note use the formula for the log-logistic cumulative distribution function (cdf) from the Burrlioz manual as these parameters were estimated in Burrlioz
      #Alpha & Beta values are exponentiated to antilog
      Haloxyfop_parameters <- data.frame(Pesticide.type = "Herbicide", Distribution.type = "Log-logistic", log.alpha = 9.736670973, alpha = 16927.09672, log.beta = 0.313737397, beta = 1.368530309)
      
  ###AChE Inhibitors
      #Alpha & Beta values are exponentiated to antilog
      Chlorpyrifos_parameters <- data.frame(Pesticide.type = "Insecticide", Distribution.type = "Burr Type III", log.b = 1.307471952, b = 3.696816161, log.c = -1.002926184, c = 0.366804532, log.k = 0.3404141, k = 1.40552947)
      
  ###ALS Inhibitors
      #Note use the formula for the log-logistic cumulative distribution function (cdf) from the Burrlioz manual as these parameters were estimated in Burrlioz
      #Alpha & Beta values are exponentiated to antilog
      Imazapic_parameters <- data.frame(Pesticide.type = "Herbicide", Distribution.type = "Log-logistic", log.alpha = 3.115540332, alpha = 22.54560918, log.beta = -0.287699081, beta = 0.749987243)
      
      #Alpha & Beta values are exponentiated to antilog
      Metsulfuron_parameters <- data.frame(Pesticide.type = "Herbicide", Distribution.type = "Inverse Weibull", log.alpha = -1.350296558, alpha = 0.259163392, log.beta = -0.82416039, beta = 0.438603093)
      
  ###GABA Cl- channel Inhibitors
      #Alpha & Beta values are exponentiated to antilog
      Fipronil_parameters <- data.frame(Pesticide.type = "Insecticide", Distribution.type = "Burr Type III", log.b = -5.108354396, b = 0.006046024, log.c = -0.614167078, c = 0.541091394, log.k = 1.6728064, k = 5.3270967)
      
  ###Microtobule Synthesis Inhibitors
      #Alpha & Beta values are exponentiated to antilog
      Pendimethalin_parameters <- data.frame(Pesticide.type = "Herbicide", Distribution.type = "Burr Type III", log.b = 1.181856154, b = 3.260420431, log.c = -0.334798726, c = 0.71548208, log.k = 0.4320021, k = 1.54033831)
      
  ###Multisite Action Inhibitors
      Chlorothalonil_parameters <- data.frame(Pesticide.type = "Fungicide", Note = "Not included at this stage")
  
  ###Neonicitinoids
      #Alpha & Beta values are exponentiated to antilog
      Imidacloprid_parameters <- data.frame(Pesticide.type = "Insecticide", Distribution.type = "Inverse Weibull", log.alpha = -0.689527, alpha = 0.501813371, log.beta = -0.173493, beta = 0.840723036)
      
  ###PSII Herbicides
      #Alpha & Beta values are exponentiated to antilog
      Ametryn_parameters <- data.frame(Pesticide.type = "Herbicide", Distribution.type = "Burr Type III", log.b = 1.70321271129072, b = 5.491562, log.c = 0.051791759, c = 1.053156, log.k = 0.027215171, k = 1.027589)
      
      #Alpha & Beta values are exponentiated to antilog
      Atrazine_parameters <- data.frame(pesticide.type = "Herbicide", Distribution.type = "Burr Type III", log.b = 2.435718313, b = 11.42402, log.c = -0.380527521, c = 0.6835008, log.k = 0.556916028, k = 1.745282)
      
      #Note use the formula for the log-logistic cumulative distribution function (cdf) from the Burrlioz manual as these parameters were estimated in Burrlioz
      #Alpha & Beta values are exponentiated to antilog
      Bromacil <- data.frame(Pesticide.type = "Herbicide", Distribution.type = "Log-Logistic", log.alpha = 2.318335968, alpha = 10.15876, log.beta = -0.117259051, beta = 0.8893548)
      
      #Alpha & Beta values are exponentiated to antilog
      Prometryn_parameters <- data.frame(Pesticide.type = "Herbicide", Distribution.type = "Burr Type III", log.b = 1.945054953, b = 6.994016, log.c = 0.004043219, c = 1.004051, log.k = 0.046399659, k = 1.047493)
      
      #Note use the formula for the log-logistic cumulative distribution function (cdf) from the Burrlioz manual as these parameters were estimated in Burrlioz
      #Alpha & Beta values are exponentiated to antilog
      Tebuthiuron_parameters <- data.frame(Pesticide.type = "Herbicide", Distribution.type = "Log-logistic", log.alpha = 3.973218745, alpha = 53.15535, log.beta = 0.642836234, beta = 1.901867)
      
      #Alpha & Beta values are exponentiated to antilog
      Terbuthylazine_parameters <- data.frame(Pesticide.type = "Herbicide", Distribution.type = "Burr Type III", log.b = 1.579371269, b = 4.851904, log.c = -0.082197727, c = 0.9210898, log.k = 0.732467232, k = 2.080207)
      
      #Note use the formula for the log-logistic cumulative distribution function (cdf) from the Burrlioz manual as these parameters were estimated in Burrlioz
      #Alpha & Beta values are exponentiated to antilog
      Fluometuron_parameters <- data.frame(Pesticide.type = "Herbicide", Distribution.type = "Log-Logistic", log.alpha = 4.945979068, alpha = 140.6084, log.beta = 0.749108486, beta = 2.115114)
      
      #Alpha & Beta values are exponentiated to antilog
      Simazine_parameters <- data.frame(Pesticide.type = "Herbicide", Distribution.type = "Burr Type III", log.b = 4.660057347, b = 105.6421, log.c = 0.716940996, c = 2.048158, log.k = 0.186694505, k = 1.205259)
      
      #Alpha & Beta values are exponentiated to antilog
      Diuron_parameters <- data.frame(Pesticide.type = "Herbicide", Distribution.type = "Burr Type III", log.b = -3.093033062, b = 0.04536415, log.c = -0.682096599, c = 0.5055559, log.k = 2.079757129, k = 8.002525)
      
      #Alpha & Beta values are exponentiated to antilog
      Terbutryn_parameters <- data.frame(Pesticide.type = "Herbicide", Distribution.type = "Burr Type III", log.b = 0.97132771, b = 2.641449, log.c = -0.601273034, c = 0.5481134, log.k = 0.782565245, k = 2.187075)
      
      #Alpha & Beta values are exponentiated to antilog
      Hexazinone_parameters <- data.frame(Pesticide.type = "Herbicide", Distribution.type = "Inverse Weibull", local.log.alpha = 0.258963617, local.alpha = 1.295586667, local.log.beta = -1.76241848, local.beta = 0.17162928)
      
      #Alpha & Beta values are exponentiated to antilog
      Metribuzin_parameters <- data.frame(Pesticide.type = "Herbicide", Distribution.type = "Inverse Weibull", local.log.alpha = 0.5369, local.alpha = 1.710695478, local.log.beta = -1.58798, local.beta= 0.20433796) 
  
  
  ###Synthetic Auxins
      #Alpha & Beta values are exponentiated to antilog
      `2,4-D_parameters` <- data.frame(Pesticide.type = "Herbicide", Distribution.type = "Inverse Weibull", log.alpha = -0.658974563, alpha = 0.5173816, log.beta = -4.936336367, beta = 0.007180858)
      
      #Alpha & Beta values are exponentiated to antilog
      MCPA_parameters <- data.frame(Pesticide.type = "Herbicide", Distribution.type = "Burr Type III", log.b = 10.24155642, b = 28044.74, log.c = 0.219595444, c = 1.245573, log.k = -1.409133471, k = 0.2443549)
      
      #Note use the formula for the log-logistic cumulative distribution function (cdf) from the Burrlioz manual as these parameters were estimated in Burrlioz
      #Alpha & Beta values are exponentiated to antilog
      Fluroxypyr_parameters <- data.frame(Pesticide.type = "Herbicide", Distribution.type = "Log-logistic", log.alpha = 7.187286375, alpha = 1322.51, log.beta = 0.628023319, beta = 1.873903)
      
      #Alpha & Beta values are exponentiated to antilog
      Triclopyr_parameters <- data.frame(Pesticide.type = "Herbicide", Distribution.type = "Burr Type III", log.b = 6.962690537, b = 1056.472, log.c = 1.700066731, c = 5.474313, log.k = -2.312677626, k = 0.09899582)
      
    ###VLFCA Inhibitors
      #Alpha & Beta values are exponentiated to antilog
      Metolachlor_parameters <- data.frame(Pesticide.type = "Herbicide", Distribution.type = "Burr Type III", log.b = 6.386127229, b = 593.5534261, log.c = -0.288986309, c = 0.74902246, log.k = -0.6023196, k = 0.54754006)
      
  
  ###############
  #PAF PSII'S TAB
  ###############
  #For each specified chemical this function will:
  #Retrieve data from pesticide_dataset
  #Use the SSD formulas from Burrlioz 2.0 (CSIRO) to calculate PAF for each sample using the estimated parameters specified above.
  #Warning: Changes must not be made to the PAF PSII'S TAB
      
        #The Burr Type III distribution is used for Ametryn
        Ametryn_PAF <- 1/(1+(Ametryn_parameters$b/pesticide_dataset$Ametryn)^Ametryn_parameters$c)^Ametryn_parameters$k*100
        PAF_propn_Ametryn <- Ametryn_PAF/100
        
        #The Burr Type III distribution is used for Atrazine
        Atrazine_PAF <- 1/(1+(Atrazine_parameters$b/pesticide_dataset$Atrazine)^Atrazine_parameters$c)^Atrazine_parameters$k*100
        PAF_propn_Atrazine <- Atrazine_PAF/100
        
        #The Burr Type III distribution is used for Prometryn
        Prometryn_PAF <- 1/(1+(Prometryn_parameters$b/pesticide_dataset$Prometryn)^Prometryn_parameters$c)^Prometryn_parameters$k*100
        PAF_propn_Prometryn <- Prometryn_PAF/100
        
        #The log-Logistic distribution is used for Tebuthiuron
        Tebuthiuron_PAF <- 1/(1+(pesticide_dataset$Tebuthiuron/Tebuthiuron_parameters$alpha)^(-1*Tebuthiuron_parameters$beta))*100
        PAF_propn_Tebuthiuron <- Tebuthiuron_PAF/100

        #The Burr Type III distribution is used for Terbuthylazine
        Terbuthylazine_PAF <- 1/(1+(Terbuthylazine_parameters$b/pesticide_dataset$Terbuthylazine)^Terbuthylazine_parameters$c)^Terbuthylazine_parameters$k*100
        PAF_propn_Terbuthylazine <- Terbuthylazine_PAF/100
        
        #The Burr Type III distribution is used for Simazine
        Simazine_PAF <- 1/(1+(Simazine_parameters$b/pesticide_dataset$Simazine)^Simazine_parameters$c)^Simazine_parameters$k*100
        PAF_propn_Simazine <- Simazine_PAF/100
        
        #The Burr Type III distribution is used for Diuron
        Diuron_PAF <- 1/(1+(Diuron_parameters$b/pesticide_dataset$Diuron)^Diuron_parameters$c)^Diuron_parameters$k*100
        PAF_propn_Diuron <- Diuron_PAF/100
        
        #The Inverse Weibull distribution is used for Hexazinone
        Hexazinone_PAF <- exp(-1/((pesticide_dataset$Hexazinone*Hexazinone_parameters$local.beta)^Hexazinone_parameters$local.alpha))*100
        PAF_proptn_Hexazinone <- Hexazinone_PAF/100
        
        #The Inverse Weibull distribution is used for Metribuzin
        Metribuzin_PAF <- exp(-1/((pesticide_dataset$Metribuzin*Metribuzin_parameters$local.beta)^Metribuzin_parameters$local.alpha))*100
        PAF_proptn_Metribuzin <- Metribuzin_PAF/100
        

        ##The independent action model of joint action is applied to PSIIs
        IA_Table_PAF_PSIIs <- data.frame(1-PAF_propn_Ametryn, 1-PAF_propn_Atrazine, 1-PAF_propn_Prometryn,
                                         1-PAF_propn_Tebuthiuron, 1-PAF_propn_Terbuthylazine, 1-PAF_propn_Simazine,
                                         1-PAF_propn_Diuron, 1-PAF_proptn_Hexazinone, 1-PAF_proptn_Metribuzin)
        
        PAF_All_PSIIs <- (1-(apply(IA_Table_PAF_PSIIs, 1, FUN=prod, na.rm=TRUE)))*100
        
        #Adding STATION, SITENAME, SAMPLING.YEAR, SAMPLING.DATE columns in the dataset
        PAF_All_PSIIs_withdate <- data.frame(STATION, SITENAME, SAMPLING.YEAR, SAMPLING.DATE, PAF_All_PSIIs)
        
        PAF_All_PSIIs_proptn <- PAF_All_PSIIs/100
 
        
        
  ####################
  #PAF OTHER HERBS TAB
  ####################
  #For each specified chemical this function will:
  #Retrieve data from pesticide_dataset
  #Use the SSD formulas from Burrlioz 2.0 (CSIRO) to calculate PAF for each sample using the estimated parameters specified above.
  #Warning: Changes must not be made to the PAF OTHER HERBS TAB
        
        #The Inverse Weibull distribution is used for Isoxaflutole
        Isoxaflutole_PAF <- exp(-1/((pesticide_dataset$Isoxaflutole*Isoxaflutole_parameters$beta)^Isoxaflutole_parameters$alpha))*100
        PAF_propn_Isoxaflutole <- Isoxaflutole_PAF/100
        
        #The log-Logistic distribution is used for Haloxyfop
        Haloxyfop_PAF <- 1/(1+(pesticide_dataset$Haloxyfop/Haloxyfop_parameters$alpha)^(-1*Haloxyfop_parameters$beta))*100
        PAF_propn_Haloxyfop <- Haloxyfop_PAF/100

        #The log-Logistic distribution is used for Imazapic
        Imazapic_PAF <- 1/(1+(pesticide_dataset$Imazapic/Imazapic_parameters$alpha)^(-1*Imazapic_parameters$beta))*100
        PAF_propn_Imazapic <- Imazapic_PAF/100
        
        #The Inverse Weibull distribution is used for Metsulfuron
        Metsulfuron_PAF <- exp(-1/((pesticide_dataset$Metsulfuron*Metsulfuron_parameters$beta)^Metsulfuron_parameters$alpha))*100
        PAF_propn_Metsulfuron <- Metsulfuron_PAF/100
        
        #The Burr Type III distribution is used for Pendimethalin
        Pendimethalin_PAF <- 1/(1+(Pendimethalin_parameters$b/pesticide_dataset$Pendimethalin)^Pendimethalin_parameters$c)^Pendimethalin_parameters$k*100
        PAF_propn_Pendimethalin <- Pendimethalin_PAF/100
        
        #The Inverse Weibull distribution is used for 2,4-D
        `2,4-D_PAF` <- exp(-1/((pesticide_dataset$X.2.4.D*`2,4-D_parameters`$beta)^`2,4-D_parameters`$alpha))*100
        `PAF_propn_2,4-D` <- `2,4-D_PAF`/100
        
        #The Burr Type III distribution is used for MCPA
        MCPA_PAF <- 1/(1+(MCPA_parameters$b/pesticide_dataset$MCPA)^MCPA_parameters$c)^MCPA_parameters$k*100
        PAF_propn_MCPA <- MCPA_PAF/100
        
        #The log-Logistic distribution is used for Fluroxypyr
        Fluroxypyr_PAF <- 1/(1+(pesticide_dataset$Fluroxypyr/Fluroxypyr_parameters$alpha)^(-1*Fluroxypyr_parameters$beta))*100
        PAF_propn_Fluroxypyr <- Fluroxypyr_PAF/100
        
        #The Burr Type III distribution is used for Triclopyr
        Triclopyr_PAF <- 1/(1+(Triclopyr_parameters$b/pesticide_dataset$Triclopyr)^Triclopyr_parameters$c)^Triclopyr_parameters$k*100
        PAF_propn_Triclopyr <- Triclopyr_PAF/100
        
        #The Burr Type III distribution is used for Metolachlor
        Metolachlor_PAF <- 1/(1+(Metolachlor_parameters$b/pesticide_dataset$Metolachlor)^Metolachlor_parameters$c)^Metolachlor_parameters$k*100
        PAF_propn_Metolachlor <- Metolachlor_PAF/100
        
        
        #The independent action model of joint action is applied to Other Herbicides
        IA_Table_PAF_Other_Herbicides <- data.frame(1-PAF_propn_Isoxaflutole, 1-PAF_propn_Haloxyfop, 
                                                      1-PAF_propn_Imazapic, 1-PAF_propn_Metsulfuron, 
                                                      1-PAF_propn_Pendimethalin, 1-`PAF_propn_2,4-D`, 1-PAF_propn_MCPA,
                                                      1-PAF_propn_Fluroxypyr, 1-PAF_propn_Triclopyr, 1-PAF_propn_Metolachlor)
        
        
        PAF_Other_Herbicides <- (1-(apply(IA_Table_PAF_Other_Herbicides, 1, FUN=prod, na.rm=TRUE)))*100
        
        #Adding STATION, SITENAME, SAMPLING.YEAR, SAMPLING.DATE columns in the dataset
        PAF_Other_Herbicides_withdate <- data.frame(STATION, SITENAME, SAMPLING.YEAR, SAMPLING.DATE, PAF_Other_Herbicides)
        
        PAF_Other_Herbicides_proptn <- PAF_Other_Herbicides/100
        
  
  
  ######################
  #PAF INSECTICIDES TAB
  ######################
  #For each specified chemical this function will:
  #Retrieve data from pesticide_dataset
  #Use the SSD formulas from Burrlioz 2.0 (CSIRO) to calculate PAF for each sample using the estimated parameters specified above.
  #Warning: Changes must not be made to the PAF INSECTICIDES TAB
        
  #The Burr Type III distribution is used for Chlorpyrifos
  Chlorpyrifos_PAF <- 1/(1+(Chlorpyrifos_parameters$b/pesticide_dataset$Chlorpyrifos)^Chlorpyrifos_parameters$c)^Chlorpyrifos_parameters$k*100
  PAF_propn_Chlorpyrifos <- Chlorpyrifos_PAF/100
  
  #The Burr Type III distribution is used for Fipronil
  Fipronil_PAF <- 1/(1+(Fipronil_parameters$b/pesticide_dataset$Fipronil)^Fipronil_parameters$c)^Fipronil_parameters$k*100
  PAF_propn_Fipronil <- Fipronil_PAF/100
  
  #The Inverse Weibull distribution is used for Imidacloprid
  Imidacloprid_PAF <- exp(-1/((pesticide_dataset$Imidacloprid*Imidacloprid_parameters$beta)^Imidacloprid_parameters$alpha))*100
  PAF_propn_Imidacloprid <- Imidacloprid_PAF/100
  
  
  #The independent action model of joint action is applied to Insecticides
  IA_Table_PAF_Insecticides <- data.frame(1-PAF_propn_Chlorpyrifos, 1-PAF_propn_Fipronil, 1-PAF_propn_Imidacloprid)
  
  PAF_Insecticides <- (1-(apply(IA_Table_PAF_Insecticides, 1, FUN=prod, na.rm=TRUE)))*100
  
  #Adding STATION, SITENAME, SAMPLING.YEAR, SAMPLING.DATE columns in the dataset
  PAF_Insecticides_withdate <- data.frame(STATION, SITENAME, SAMPLING.YEAR, SAMPLING.DATE, PAF_Insecticides)
  
  PAF_Insecticides_proptn <- PAF_Insecticides/100
  
  
  ###############
  #PAF TOTAL TAB
  ###############
  #Warning: Changes must not be made to the PAF TOTAL TAB
  
  #1-PAF FOR PSII'S, OTHER HERBICIDES AND INSECTICIDES
  
  IA_Table_Total <- cbind(IA_Table_PAF_PSIIs, IA_Table_PAF_Other_Herbicides, IA_Table_PAF_Insecticides)
  
  PAF_Total <- (1-(apply(IA_Table_Total, 1, FUN=prod, na.rm=TRUE)))*100
  
  #Adding STATION, SITENAME, SAMPLING.YEAR, SAMPLING.DATE columns in the dataset
  PAF_Total_withdate <- data.frame(STATION, SITENAME, SAMPLING.YEAR, SAMPLING.DATE, PAF_Total)
  
  PAF_Total_proptn <- PAF_Total/100
  
  
  ###################
  #DAILY AVERAGE TAB
  ###################
  
  Daily_Average_Function <- function(PAF_Values){
    
   Daily_Ave <- aggregate(PAF_Values, by = list(STATION, SITENAME, SAMPLING.YEAR, SAMPLING.DATE) , FUN = mean)
    
    names(Daily_Ave) <- c("STATION", "SITENAME", "Sampling.Year", "DATE", "Daily.Ave.PAF")
    
    Daily_Ave
    
  }
  
  #PAF VALUES FOR EACH CHEMICAL
  Daily_PAF_Chemicals <- data.frame(SITENAME, STATION, SAMPLING.YEAR, SAMPLING.DATE, Ametryn_PAF, Atrazine_PAF, Diuron_PAF, Hexazinone_PAF, Metribuzin_PAF, Prometryn_PAF, 
                                    Simazine_PAF,Tebuthiuron_PAF, Terbuthylazine_PAF, Isoxaflutole_PAF, Haloxyfop_PAF, Imazapic_PAF, 
                                    Metsulfuron_PAF, Pendimethalin_PAF,  `2,4-D_PAF`, MCPA_PAF, Triclopyr_PAF, Fluroxypyr_PAF,
                                    Metolachlor_PAF, Chlorpyrifos_PAF, Fipronil_PAF, Imidacloprid_PAF)
  
  
  #EXPORT TABLES
  
  #write.csv(Daily_PAF_Chemicals, paste(path_Daily_Average_RA_PAF_Output_PSIIs, paste(paste(unique(SITENAME), unique(SAMPLING.YEAR), "PAF_Chemicals", "msPAF22", "SH", sep="_"), ".csv", sep=""), sep=""), row.names = FALSE)
  #write.csv(Daily_PAF_Chemicals, paste(output_path, paste("PAF_All_Chemicals", "msPAF22", Sys.getenv("USERNAME"), as.character(Sys.Date()), sep="_"), ".csv", sep=""), row.names = FALSE)
  
 Daily_Average_IA_PAF_PSIIs <- Daily_Average_Function(PAF_All_PSIIs)
  #Ensure that there are no 0's in the Daily Average PAF values as they will be logged
  Daily_Average_IA_PAF_PSIIs$Daily.Ave.PAF <- ifelse(Daily_Average_IA_PAF_PSIIs$Daily.Ave.PAF == 0, 0.00000000001, Daily_Average_IA_PAF_PSIIs$Daily.Ave.PAF)
  
  write.csv(Daily_Average_IA_PAF_PSIIs, paste(output_path, paste("PAF_All_PSIIs_Daily_Average", "msPAF22", Sys.getenv("USERNAME"), as.character(Sys.Date()), sep="_"), ".csv", sep=""), row.names = FALSE)
  
  
  Daily_Average_IA_PAF_Other_Herbicides <- Daily_Average_Function(PAF_Other_Herbicides)
  #Ensure that there are no 0's in the Daily Average PAF values as they will be logged
  Daily_Average_IA_PAF_Other_Herbicides$Daily.Ave.PAF <- ifelse(Daily_Average_IA_PAF_Other_Herbicides$Daily.Ave.PAF == 0, 0.00000000001, Daily_Average_IA_PAF_Other_Herbicides$Daily.Ave.PAF)
  
  write.csv(Daily_Average_IA_PAF_Other_Herbicides, paste(output_path, paste("PAF_Other_Herbicides_Daily_Average", "msPAF22", Sys.getenv("USERNAME"), as.character(Sys.Date()), sep="_"), ".csv", sep=""), row.names = FALSE)
  
  
  Daily_Average_IA_PAF_Insecticides <- Daily_Average_Function(PAF_Insecticides)
  #Ensure that there are no 0's in the Daily Average PAF values as they will be logged
  Daily_Average_IA_PAF_Insecticides$Daily.Ave.PAF <- ifelse(Daily_Average_IA_PAF_Insecticides$Daily.Ave.PAF == 0, 0.00000000001, Daily_Average_IA_PAF_Insecticides$Daily.Ave.PAF)
  
  write.csv(Daily_Average_IA_PAF_Insecticides, paste(output_path, paste("PAF_Insecticides_Daily_Average", "msPAF22", Sys.getenv("USERNAME"), as.character(Sys.Date()), sep="_"), ".csv", sep=""), row.names = FALSE)
  
  
Daily_Average_IA_PAF_Total <- Daily_Average_Function(PAF_Total)
  #Ensure that there are no 0's in the Daily Average PAF values as they will be logged
Daily_Average_IA_PAF_Total$Daily.Ave.PAF <- ifelse(Daily_Average_IA_PAF_Total$Daily.Ave.PAF == 0, 0.00000000001, Daily_Average_IA_PAF_Total$Daily.Ave.PAF)

write.csv(Daily_Average_IA_PAF_Total, paste(output_path, paste("PAF_Total_Daily_Average", "msPAF22", Sys.getenv("USERNAME"), as.character(Sys.Date()), sep="_"), ".csv", sep=""), row.names = FALSE)
  
}

##==============================================Calling the function==========================================##
# make sure you set your working directory to the project location so the exported files save to somewhere known. 
#setwd("N:/Event Monitoring/Data Management/msPAF calculation_22 pesticides/msPAF calculations/2021_2022 Report data/raw concentration data")
pesticide_dataset <- read.csv("Treated_LORs.csv")
pesticide_dataset$DATE.TIME.SAMPLED <- as.POSIXct(pesticide_dataset$DATE.TIME.SAMPLED, format = "%Y-%m-%d %H:%M:%S",  tz = "Australia/Brisbane")
#pesticide_dataset$DATE <- as.Date(pesticide_dataset$DATE.TIME.SAMPLED, format="%d/%m/%Y",  tz = "Australia/Brisbane")
str(pesticide_dataset)
path_Daily_Average_PAF_Output <- ""
#setwd("N:/Event Monitoring/Data Management/msPAF calculation_22 pesticides/msPAF calculations/2021_2022 Report data/R code calcs/full sampling year")
calculate_Daily_Average_IA_PAF_Categories(pesticide_dataset, path_Daily_Average_PAF_Output)

